// src/lib/components/hero/SocialBar.svelte
<script lang="ts">
	import info from '$data';
	import Icon from '@iconify/svelte';

	const iconClass =
		'p-1 select-none hover:ring-4 hover:text-white md:bg-transparent rounded-full ring-2 transition ease-in-out duration-200';
	const { socials } = info;

	type SocialKeys = keyof typeof socials;

	const size = 40;
	const colors: Record<SocialKeys, string> = {
		gmail: 'text-rose-400 ring-rose-400 hover:bg-rose-600',
		telegram: 'text-sky-400 ring-sky-400 hover:bg-sky-600',
		discord: 'text-indigo-400 ring-indigo-400 hover:bg-indigo-600',
		linkedin: 'text-blue-400 ring-blue-400 hover:bg-blue-600',
		github: 'text-gray-400 ring-gray-400 hover:bg-gray-700'
	};

	// Map social keys to iconify icons
	const iconMap: Record<SocialKeys, string> = {
		gmail: 'mdi:email',
		telegram: 'mdi:telegram',
		discord: 'mdi:discord',
		linkedin: 'mdi:linkedin',
		github: 'mdi:github'
	};
</script>

<div class="appear z-10 flex items-center justify-center md:justify-start">
	<div class="flex gap-3">
		{#each Object.keys(socials) as key (key)}
			{@const url = socials[key as SocialKeys]}
			<a target="_blank" href={url} rel="noopener noreferrer">
				<Icon
					icon={iconMap[key as SocialKeys]}
					width={size}
					height={size}
					class="{iconClass} {colors[key as SocialKeys]}"
				/>
			</a>
		{/each}
	</div>
</div>

// src/components/social/SocialBar.tsx
import Info from "@/data";
import { MotionDiv } from "@/motion";
import { AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import { BiLogoGmail, BiLogoTelegram } from "react-icons/bi";
import { BsDiscord } from "react-icons/bs";

import Button from "../button/Button";
import Social from "./Social";

const SocialBar = () => {
  const socials = Info.socials;
  return (
    <div className="flex flex-col gap-8 items-center justify-center">
      <Button className="w-56 bg-background text-secondary rounded-full ring-2 ring-primary hover:bg-primary hover:text-foreground">
        Download CV
      </Button>
      <MotionDiv
        className="flex gap-3 justify-center"
        initial={{ opacity: 0, y: 40 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <Social
          Icon={AiFillGithub}
          link={`https://github.com/${socials.github}`}
        />
        <Social
          Icon={AiFillLinkedin}
          link={`https://linkedin.com/in/${socials.linkedin}`}
        />
        <Social Icon={BiLogoGmail} link={`mailto:${socials.gmail}`} />
        <Social
          Icon={BiLogoTelegram}
          link={`https://t.me/${socials.telegram}`}
        />
        <Social
          Icon={BsDiscord}
          link={`https://discord.com/users/${socials.discord}`}
        />
      </MotionDiv>
    </div>
  );
};

export default SocialBar;
