// src/lib/components/PDFViewer.svelte
<script lang="ts">
	import { browser } from '$app/environment';
	import type { PDFDocumentProxy } from 'pdfjs-dist/types/src/display/api';
	import { onDestroy, onMount } from 'svelte';

	// Dynamic import type for pdfjs-dist
	type PdfjsLib = typeof import('pdfjs-dist');

	interface Props {
		cvPDF: string;
	}

	let { cvPDF }: Props = $props();

	let containerRef = $state<HTMLDivElement | null>(null);
	let pagesContainer = $state<HTMLDivElement | null>(null);
	let containerWidth = $state(900);
	let numPages = $state<number>(0);
	let isLoading = $state(false);
	let isRendering = $state(false);
	let error = $state<string | null>(null);
	let pdfDocument = $state<PDFDocumentProxy | null>(null);
	let pdfBlobUrl = $state<string | null>(null);
	let pdfjsLib = $state<PdfjsLib | null>(null);

	// Initialize PDF.js worker - client-only
	onMount(async () => {
		// Dynamically import pdfjs-dist only on client
		const pdfjs = await import('pdfjs-dist');
		pdfjsLib = pdfjs;

		// Set up the worker
		pdfjs.GlobalWorkerOptions.workerSrc = new URL(
			'pdfjs-dist/build/pdf.worker.min.mjs',
			import.meta.url
		).toString();

		// Handle initial resize
		handleResize();
		window.addEventListener('resize', handleResize);

		// Fetch PDF
		if (cvPDF.trim()) {
			await fetchPdf(cvPDF);
		}
	});

	onDestroy(() => {
		if (!browser) return;
		window.removeEventListener('resize', handleResize);
		if (pdfBlobUrl) {
			URL.revokeObjectURL(pdfBlobUrl);
		}
		if (pdfDocument) {
			pdfDocument.destroy();
		}
	});

	function handleResize() {
		if (containerRef) {
			containerWidth = containerRef.clientWidth;
		}
	}

	async function fetchPdf(url: string) {
		if (!pdfjsLib) return;
		
		isLoading = true;
		error = null;
		numPages = 0;

		try {
			const response = await fetch('/api/get-file-as-blob', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					'Cache-Buster': Date.now().toString()
				},
				body: JSON.stringify({ fileUrl: url.trim() })
			});

			if (!response.ok) {
				throw new Error(`Failed to load: ${response.statusText}`);
			}

			const blob = await response.blob();
			const newBlobUrl = URL.createObjectURL(blob);

			if (pdfBlobUrl) {
				URL.revokeObjectURL(pdfBlobUrl);
			}

			pdfBlobUrl = newBlobUrl;
			isRendering = true;

			// Load the PDF document
			const loadingTask = pdfjsLib.getDocument(newBlobUrl);
			pdfDocument = await loadingTask.promise;
			numPages = pdfDocument.numPages;

			// Render all pages
			await renderAllPages();
		} catch (err) {
			error = err instanceof Error ? err.message : 'Unknown error';
		} finally {
			isLoading = false;
			isRendering = false;
		}
	}

	async function renderAllPages() {
		if (!pdfDocument || !pagesContainer) return;

		// Clear existing pages
		pagesContainer.innerHTML = '';

		for (let pageNum = 1; pageNum <= numPages; pageNum++) {
			const page = await pdfDocument.getPage(pageNum);
			const scale = Math.min(containerWidth, 900) / page.getViewport({ scale: 1 }).width;
			const viewport = page.getViewport({ scale });

			// Create canvas for this page
			const canvas = document.createElement('canvas');
			canvas.className = 'mb-1 block';
			canvas.width = viewport.width;
			canvas.height = viewport.height;

			const context = canvas.getContext('2d');
			if (context) {
				await page.render({
					canvasContext: context,
					viewport
				}).promise;
			}

			pagesContainer.appendChild(canvas);
		}
	}

	async function retry() {
		if (cvPDF.trim()) {
			await fetchPdf(cvPDF);
		}
	}

	// Re-render when container width changes significantly
	$effect(() => {
		if (pdfDocument && containerWidth && pagesContainer) {
			renderAllPages();
		}
	});
</script>

<div class="flex h-full w-full max-w-4xl flex-col" bind:this={containerRef}>
	{#if error}
		<div class="flex h-full w-full items-center justify-center text-center">
			<div class="space-y-4">
				<p>Error loading PDF. Disable extensions like IDM and try again.</p>
				<button
					class="rounded-md border border-white/20 px-3 py-2 text-sm transition-colors hover:border-white/40"
					onclick={retry}
				>
					Retry
				</button>
			</div>
		</div>
	{:else if isLoading && !pdfBlobUrl}
		<div class="flex h-full w-full items-center justify-center text-center">
			<p>Loading PDF...</p>
		</div>
	{:else}
		<div class="relative flex-1 overflow-x-hidden overflow-y-auto">
			{#if isRendering}
				<div class="absolute inset-0 z-10 flex items-center justify-center">
					<p>Rendering PDF...</p>
				</div>
			{/if}
			<div class={isRendering ? 'invisible' : 'visible'} bind:this={pagesContainer}></div>
		</div>
	{/if}
</div>

// src/components/viewer/PDFViewer.tsx
import { useEffect, useRef, useState } from "react";
import { Document, Page, pdfjs } from "react-pdf";
import "react-pdf/dist/esm/Page/AnnotationLayer.css";
import "react-pdf/dist/esm/Page/TextLayer.css";

// Configure PDF.js worker
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  "pdfjs-dist/build/pdf.worker.min.mjs",
  import.meta.url,
).toString();

export default function PDFViewer({ cvPDF }: { cvPDF: string }) {
  const [numPages, setNumPages] = useState<number>();
  const containerRef = useRef<HTMLDivElement>(null);
  const [containerWidth, setContainerWidth] = useState(900);
  const [pdfBlobUrl, setPdfBlobUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Improved fetch with cache busting
  const fetchPdf = async (url: string) => {
    setIsLoading(true);
    setError(null);

    try {
      const response = await fetch("/api/get-file-as-blob", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Cache-Buster": Date.now().toString(), // Prevent stale cache
        },
        body: JSON.stringify({ fileUrl: url.trim() }),
      });

      if (!response.ok)
        throw new Error(`Failed to load: ${response.statusText}`);

      const blob = await response.blob();
      const newBlobUrl = URL.createObjectURL(blob);

      if (pdfBlobUrl) URL.revokeObjectURL(pdfBlobUrl); // Cleanup
      setPdfBlobUrl(newBlobUrl);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setIsLoading(false);
    }
  };

  // Fetch on mount and URL change
  useEffect(() => {
    if (cvPDF.trim()) fetchPdf(cvPDF);
    return () => {
      if (pdfBlobUrl) URL.revokeObjectURL(pdfBlobUrl);
    };
  }, [cvPDF]);

  // Responsive width handling
  useEffect(() => {
    const handleResize = () => {
      if (containerRef.current) {
        setContainerWidth(containerRef.current.clientWidth);
      }
    };

    handleResize();
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  return (
    <div className="max-w-4xl" ref={containerRef}>
      {isLoading && !pdfBlobUrl ? (
        <div className="pt-3">Loading PDF...</div>
      ) : error ? (
        <div className="pt-3">
          Error loading PDF. Disable extensions like IDM and try again.
          <button onClick={() => fetchPdf(cvPDF)}>Retry</button>
        </div>
      ) : (
        <Document
          file={pdfBlobUrl}
          onLoadSuccess={({ numPages }) => setNumPages(numPages)}
          loading={<div className="pt-3">Rendering PDF...</div>}
          error={<div className="pt-3">Failed to render PDF</div>}
        >
          {Array.from({ length: numPages || 0 }, (_, i) => (
            <Page
              className="mb-1"
              key={`page_${i + 1}`}
              pageNumber={i + 1}
              width={Math.min(containerWidth, 900)}
              loading={<div>Loading page {i + 1}...</div>}
            />
          ))}
        </Document>
      )}
    </div>
  );
}
